name: Run delstack

on:
  push:
    branches:
      - main

jobs:
  run-delstack:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      # - name: Configure AWS credentials
      #   uses: aws-actions/configure-aws-credentials@v3
      #   with:
      #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     aws-region: ap-northeast-1
      - uses: go-to-k/delstack@v1
      - name: Run delstack
        run: delstack -v
      - uses: go-to-k/delstack@v1
        with:
          stack-name: "test"
